<?php
$dbDriver = getenv('DB_DRIVER') ?: 'mysql';
$token = getenv('APP_SETUP_TOKEN') ?: '';
if ($dbDriver !== 'pgsql') {
    http_response_code(403);
    die('Setup solo disponible en pgsql');
}
if ($token === '' || !hash_equals($token, isset($_GET['token']) ? $_GET['token'] : '')) {
    http_response_code(403);
    die('Token inválido');
}

$pghost = getenv('DB_HOST') ?: getenv('PGHOST_UNPOOLED') ?: getenv('PGHOST');
$dsn = 'pgsql:host=' . $pghost . ';port=' . (getenv('DB_PORT') ?: getenv('PGPORT')) . ';dbname=' . (getenv('DB_NAME') ?: getenv('PGDATABASE'));
if (strpos($pghost, 'neon.tech') !== false) {
    $dsn .= ';options=endpoint=' . explode('.', $pghost)[0];
}
if (getenv('PGSSL') === '1' || getenv('DB_SSL') === '1') {
    $dsn .= ';sslmode=require';
}
try {
    $pdo = new PDO($dsn, getenv('DB_USER') ?: getenv('PGUSER'), getenv('DB_PASSWORD') ?: getenv('PGPASSWORD'));
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    http_response_code(500);
    die('Error de conexión: ' . $e->getMessage());
}

$sql = "
CREATE TABLE IF NOT EXISTS secretarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    activa SMALLINT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS oficinas_departamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    activa SMALLINT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS oficinas_secretarias (
    oficina_id BIGINT NOT NULL REFERENCES oficinas_departamentos(id) ON DELETE CASCADE,
    secretaria_id BIGINT NOT NULL REFERENCES secretarias(id) ON DELETE CASCADE,
    PRIMARY KEY (oficina_id, secretaria_id)
);
CREATE TABLE IF NOT EXISTS reparaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_equipo VARCHAR(100),
    marca VARCHAR(100),
    modelo VARCHAR(100),
    motivo TEXT,
    secretaria_origen_id BIGINT REFERENCES secretarias(id) ON DELETE SET NULL,
    oficina_origen_id BIGINT REFERENCES oficinas_departamentos(id) ON DELETE SET NULL,
    fecha_envio DATE,
    tecnico VARCHAR(100),
    costo_estimado NUMERIC(10,2),
    persona_presupuesto VARCHAR(100),
    fecha_presupuesto DATE,
    numero_orden VARCHAR(50),
    fecha_orden DATE,
    estado VARCHAR(50),
    observaciones TEXT
);
CREATE TABLE IF NOT EXISTS movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reparacion_id BIGINT NOT NULL REFERENCES reparaciones(id),
    tipo_movimiento VARCHAR(50) NOT NULL,
    descripcion TEXT,
    fecha_movimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS idx_movimientos_reparacion ON movimientos(reparacion_id);
CREATE INDEX IF NOT EXISTS idx_oficinas_secretarias_sec ON oficinas_secretarias(secretaria_id);
";
foreach (array_filter(array_map('trim', explode(';', $sql))) as $stmt) {
    if ($stmt !== '') {
        $pdo->exec($stmt);
    }
}

$count = $pdo->query("SELECT COUNT(*) FROM secretarias")->fetchColumn();
$resultado = [];
if ((int)$count === 0) {
    $pdo->exec("INSERT INTO secretarias (nombre, descripcion) VALUES ('Secretaría General', 'Administración central')");
    $sec1 = (int)$pdo->query("SELECT lastval()")->fetchColumn();
    $pdo->exec("INSERT INTO secretarias (nombre, descripcion) VALUES ('Recursos Humanos', 'Gestión de personal')");
    $sec2 = (int)$pdo->query("SELECT lastval()")->fetchColumn();

    $pdo->exec("INSERT INTO oficinas_departamentos (nombre) VALUES ('Mesa de Entradas')");
    $of1 = (int)$pdo->query("SELECT lastval()")->fetchColumn();
    $pdo->exec("INSERT INTO oficinas_departamentos (nombre) VALUES ('Liquidación de Sueldos')");
    $of2 = (int)$pdo->query("SELECT lastval()")->fetchColumn();

    $pdo->exec("INSERT INTO oficinas_secretarias (oficina_id, secretaria_id) VALUES ($of1, $sec1), ($of2, $sec2)");

    $pdo->exec("INSERT INTO reparaciones (tipo_equipo, marca, modelo, motivo, secretaria_origen_id, oficina_origen_id, fecha_envio, tecnico, estado, observaciones)
                VALUES ('PC de escritorio', 'Dell', 'Optiplex', 'No enciende', $sec1, $of1, '2023-10-01', 'Juan Perez', 'En reparación', 'Posible falla de fuente')");
    $rep = (int)$pdo->query("SELECT lastval()")->fetchColumn();

    $pdo->exec("INSERT INTO movimientos (reparacion_id, tipo_movimiento, descripcion, usuario) VALUES
                ($rep, 'estado', 'Estado inicial: Enviado', 'Sistema'),
                ($rep, 'estado', 'Cambio de estado a: En reparación', 'Sistema')");

    $resultado[] = 'Seed insertado';
} else {
    $resultado[] = 'Datos existentes, seed omitido';
}

header('Content-Type: application/json');
echo json_encode(['success' => true, 'mensajes' => $resultado]);